import axios from "axios";

const Axios = axios.create({
    timeout: 1000 * 30
});
Axios.interceptors.request.use(async config => {
    const token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiU2VwdGlhbiBGZXJpIEZlcmRpbmFuIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdpQjM3OUVuNHREWmlCaHFRNDRIbE5pNHZ1VGg4SFhtUkpEbjA1ZExnPXM5Ni1jIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FydmlzLWRldiIsImF1ZCI6ImFydmlzLWRldiIsImF1dGhfdGltZSI6MTYxNzYwMTQ2MiwidXNlcl9pZCI6InA4TlZMQVI5WjdaSHJZMmozTHNWdVNOZ1FpSjIiLCJzdWIiOiJwOE5WTEFSOVo3WkhyWTJqM0xzVnVTTmdRaUoyIiwiaWF0IjoxNjE3NjAxNDYyLCJleHAiOjE2MTc2MDUwNjIsImVtYWlsIjoiZmVyaS5mZXJkaW5hbjc5QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTE0NzQzOTMxOTM1MDU2NTA3MjY1Il0sImVtYWlsIjpbImZlcmkuZmVyZGluYW43OUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.ZI1Io0j4JsqJnxIEl2WBT7iKHsp8-OPgySyZb6IQuOIhM6g9ZghSSzefstgGSxiEPy5zOZOYzpOYpXoyf-2kl7NdDwNvOXuWugGj6dZJZm08aTkEGKY7kf4lACht0NpLb-lSg-bAkCSQvBVwmoGUUbJ6rsx7g7f0w0y4MT7fnN4QXuzJt2fqZvUmAIxBEF3LmG-vPcnH_4QB4zv1cuNGMsZqerkD6ztJepxW96cbMtrWTy9F_68BKWmFUDtqD73FNOlFrfqvzVfJCis6VUnR0Kgu3SCY3yCKv-HW9ALIKcxFnP5GrIoquaoibWYx11lrpdOghhPx-86AFMwLwhTCwQ"
    const baseURL = "https://www.arvis-dev.online/"
    config.baseURL = baseURL
    config.headers.Authorization = `Bearer ${token}`;
    return config;
});

export default Axios